insert into video (titulo, descricao, url) values ("Docker", "Iniciando MySQL com Docker", "https://www.youtube.com/watch?v=1Zpr1vX0wqk");
insert into video (titulo, descricao, url) values ("Promoção Bumerangue", "PROMOÇÃO LATAMPASS BUMERANGUE & LIVELO 133%", "https://www.youtube.com/watch?v=uYTTovmw3ME");
insert into video (titulo, descricao, url) values ("Cartão Mercado PAGO", "CARTÃO DE CRÉDITO MP", "https://www.youtube.com/watch?v=Ve9MyFiZkMw");
insert into video (titulo, descricao, url) values ("Ações BB Seguridade", "Vale a pena investir nas Ações da BB Seguridade", "https://www.youtube.com/watch?v=T7HsVka7tPE");
insert into video (titulo, descricao, url) values ("Corona", "CoronaVirus Brasil 28/07", "https://www.youtube.com/watch?v=cwV12y7n3Jw");
insert into video (titulo, descricao, url) values ("What if?", "E Se hitler tivesse vencido a segunda guerra", "https://www.youtube.com/watch?v=Jhcr172zeCg");
insert into video (titulo, descricao, url) values ("Curiosidades da Construção", "Os Erros De Construção Mais Caros Da História", "https://www.youtube.com/watch?v=30twi2vk22E");
insert into video (titulo, descricao, url) values ("C6 Bank vai falir?", "É Seguro deixar seu dinheiro no C6 Bank?", "https://www.youtube.com/watch?v=BrC0qHWi1Gg");
insert into video (titulo, descricao, url) values ("Docker 2", "Iniciando MySQL com Docker 2", "https://www.youtube.com/watch?v=1Zpr1vX0wqk");
